# Generated by Django 3.0.3 on 2020-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewuserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('emailid', models.EmailField(max_length=254)),
                ('contactno', models.IntegerField()),
                ('dateofbirth', models.DateField()),
                ('companynaem', models.CharField(max_length=30)),
            ],
        ),
    ]
